//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Credential
    {
        public Credential()
        {
            this.Employees = new HashSet<Employee>();
        }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Username ")]
        public string username { get; set; }
        [DisplayName("Password ")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required.")]
        public string password { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string LoginErrorMessage { get; set; }
        public string RegistrationSuccessMessage { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }

    public class UserProfile
    {
        public string newUsername { get; set; }
        [DataType(DataType.Password)]
        public string oldPassword { get; set; }
        [DataType(DataType.Password ,ErrorMessage ="Do not exceed 8 Characters")]
        public string newPassword { get; set; }
        [DataType(DataType.EmailAddress, ErrorMessage ="Please enter a vaild Email Address.")]
        public string newEmail { get; set; }
        [Required(ErrorMessage = "Phone Number Required!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string newPhone { get; set; }
    }
}
